<?xml version="1.0" encoding="UTF-8"?><testrun name="Runner" project="Advantage" tests="1" started="1" failures="1" errors="0" ignored="0">
  <testsuite name="br.com.advantage.runner.Runner" time="38.794">
    <testsuite name="Consulta" time="38.794">
      <testcase name="Adicionar item no carrinho" classname="Consulta" time="38.794">
        <failure>java.lang.AssertionError&#13;
	at org.junit.Assert.fail(Assert.java:87)&#13;
	at org.junit.Assert.assertTrue(Assert.java:42)&#13;
	at org.junit.Assert.assertTrue(Assert.java:53)&#13;
	at br.com.advantage.logic.ConsultarAdicionarLogic.validaItemAdicionado(ConsultarAdicionarLogic.java:67)&#13;
	at br.com.advantage.steps.ConsultarAdicionarStep.valido_que_o_item_foi_adicionado(ConsultarAdicionarStep.java:110)&#13;
	at âœ½.valido que o item foi adicionado(classpath:features/consultarAdicionar/consultarAdicionar.feature:43)&#13;
&#13;
</failure>
      </testcase>
    </testsuite>
  </testsuite>
</testrun>
